### ISSUE TITLE
Packaging for Guix System

### ISSUE THREAD

**Issue by musicsd** [gi-lom/dialect#101]
Please package this app for Guix System as well; Thanks

**Comment by fushinari** [comment]
I'm sorry but any packaging other than Flatpak and AUR is by the community. Even the AUR package is just there because I use Arch and am able to support it (It still has no guarantees of on-time updates due to time constraints).

Neither of us (the current maintainers) are able dedicate the time and energy required to package and test for multiple distributions or package managers.

As has already happened with Fedora, let's hope that other package maintainers pick up Dialect for packaging.
