### ISSUE TITLE
Show pinyin for Chinese translations

### ISSUE THREAD

**Issue by cwmke** [gi-lom/dialect#108]
For Chinese language learners the Pinyin that shows up underneath the characters can be very helpful. Does the api expose that at all? It is shown in the below image `nǐ hǎo`. Thanks for creating this fantastic application!

![image](https://user-images.githubusercontent.com/1923967/101950417-de08b300-3bba-11eb-9766-83dcd43f54c8.png)

**Comment by fushinari** [comment]
The API does expose it. Not elegantly, but yes it does. So yes, we can add it. :smile:

**Comment by fushinari** [comment]
This was easy to implement but needs some polish.

One-line text is fine:
![Screenshot_20201212_110236](https://user-images.githubusercontent.com/28823274/101976280-b3c1fe80-3c69-11eb-80d5-98c96a69d388.png)

Multiple lines is not. We need scrolling because too much text will force the app UI to scale. But using a GtkScrolledWindow forces the scrollbar to appear even if there are only two lines of text:
![Screenshot_20201212_111622](https://user-images.githubusercontent.com/28823274/101976462-7a8a8e00-3c6b-11eb-9d20-2868948b78ec.png)

@rafaelmardojai what do you think?
