### ISSUE TITLE
Submit to Flathub

### ISSUE THREAD

**Issue by gi-lom** [gi-lom/dialect#24]
https://github.com/flathub/flathub/wiki/App-Requirements

**Comment by fushinari** [comment]
- [ ] App ID
- [ ] Appstream metadata
- [ ] Stable tagged release

These are the things that are left. But before the tagged release, there's some work necessary:

- [ ] Can anyone confirm if the live search feature is working reliably?
- [ ] Fix #17 . This is important because blocking UI actions during processing is bad design. An easy workaround would be to use a Python thread. It will work but not as elegantly as we would want.
- [ ] Same issue as #17 but for normal translation. I've worked around this for live search by using `GLib.idle_add()`. Again, we have two options here: synchronously queuing the calls in the GLib main loop or asynchronous calls. First one is easier and second one is probably neater.

**Comment by rafaelmardojai** [comment]
>  Can anyone confirm if the live search feature is working reliably?

It stutters a bit, a solution is to run the translator in a different Thread. The elegant solution would be to use `asyncio` if we get it to work.

**Comment by fushinari** [comment]
> It stutters a bit, a solution is to run the translator in a different Thread. The elegant way would be to use `asyncio` if we get it to work.

asyncio would be the right way but we'd have to depend on gbulb which is a dead project or asyncio_glib which is unpackaged on most distributions. Or we'd have to write our our own little wrapper. At least that's what I'm understanding... am I wrong?

**Comment by gi-lom** [comment]
> > It stutters a bit, a solution is to run the translator in a different Thread. The elegant way would be to use `asyncio` if we get it to work.
> 
> asyncio would be the right way but we'd have to depend on gbulb which is a dead project or asyncio_glib which is unpackaged on most distributions. Or we'd have to write our our own little wrapper. At least that's what I'm understanding... am I wrong?

I tried using Asyncio-glib, but I think we need someone more expert. 

> > Can anyone confirm if the live search feature is working reliably?
> 
> It stutters a bit, a solution is to run the translator in a different Thread. The elegant way would be to use `asyncio` if we get it to work.

I found it hard to find help for getting asyncio-glib to work. What is a very good reason not to use threads?

**Comment by fushinari** [comment]
I have no experience with `asyncio`. I've used `concurrent.futures` in Reo and have used threading in the past, but that's all. So yeah, we need someone.

**Comment by rafaelmardojai** [comment]
I was able to use asyncio with GLib using gbulb when I was working on [Telex](https://www.github.com/rafaelmardojai/Telex/tree/master/src/application.py). But I don't know how is working with recent python and asyncio-glib. 

I will give it a try, buy I can't promise anything. 😂

For now we can just use Threads to get the work done.

**Comment by rafaelmardojai** [comment]
> asyncio_glib which is unpackaged on most distributions. Or we'd have to write our our own little wrapper.

If we get it to work we can include asyncio-glib on our source code, it's pretty small.

**Comment by fushinari** [comment]
> I was able to use asyncio with GLib using gbulb when I was working on [Telex](https://www.github.com/rafaelmardojai/Telex/tree/master/src/application.py). But I don't know how is working with recent python and asyncio-glib. 

Nice. Telex looks amazing btw.

> I will give it a try, but I can't promise anything. 😂

That's the best bet we have 😆
 
> For now we can just use Threads to get the work done.

About that, do we only want one thread running at a time or do we want more?

**Comment by rafaelmardojai** [comment]
I failed making asyncio-glib work. It worked partially, but not as expected. I will try other approaches later with more time.

But for now let's just use standard python threading.

**Comment by fushinari** [comment]
Yes, how about ensuring that only one thread runs at a time? I mean, using a GtkSpinner when one thread is still trying to get the audio?

**Comment by rafaelmardojai** [comment]
What do you mean? `GLib.idle_add` should work to update the UI.

**Comment by fushinari** [comment]
I mean, for the audio, let's substitute the "Play" button with a GtkSpinner (still keeping the rest of the UI unblocked) when clicked and re-enable the play button when the thread finishes its job.

This is also important for the translation too. Multiple requests will lead to a race condition. So the request must be queued, ideally also while ignoring some requests in cases like this:
- A user types and clicks translate (Request 1)
- Quickly rewrites and then clicks translate again before Request 1 is complete (Request 2). This request should be queued.
- Rewrites again before Request 1 is complete and clicks translate (Request 3). This request should cause Request 2 to be deleted since the completion of Request 2 is not necessary anymore.

This is for preventing API abuse.

**Comment by rafaelmardojai** [comment]
Right, LGTM.

**Comment by rafaelmardojai** [comment]
Current app sumary is: `A translation app for GTK environments based on Google Translate.`

What about something like: `Google Translate client for GNOME`?

**Comment by rafaelmardojai** [comment]
@fushinari I see that you changed it to `A translation app for GNOME based on Google Translate.` in the README.

**Comment by fushinari** [comment]
Yeah, I did. But yeah, maybe we should drop the "based on Google Translate" from the short description

**Comment by fushinari** [comment]
Are we actually done now?

**Comment by rafaelmardojai** [comment]
> Are we actually done now?

Yes, I think we're ready for a release.

**Comment by fushinari** [comment]
> Yes, I think we're ready for a release.

0.1.0?

**Comment by rafaelmardojai** [comment]
The app is pretty polished at this point, I would go with 1.0.0 

What do you think?

**Comment by fushinari** [comment]
True, let's go with that. I'm a bit busy at the moment so could you do the honors? :)

**Comment by rafaelmardojai** [comment]
Done! I will submit it to Flathub later today.

**Comment by rafaelmardojai** [comment]
Dialect as been submitted to Flathub! https://github.com/flathub/com.github.gi_lom.dialect

After a few hours it should appear in https://flathub.org/
