### ISSUE TITLE
AUR package does not work with Manjaro

### ISSUE THREAD

**Issue by aaronrancsik** [gi-lom/dialect#65]
```Traceback (most recent call last):
File "/usr/bin/dialect", line 33, in <module>
  from dialect import main
File "/usr/share/dialect/dialect/main.py", line 13, in <module>
  gi.require_version('Handy', '1')
File "/usr/lib/python3.8/site-packages/gi/__init__.py", line 132, in require_version
  raise ValueError('Namespace %s not available for version %s' %
ValueError: Namespace Handy not available for version 1
```
- Installed from AUR.
- OS: Manjaro latest.

**Comment by fushinari** [comment]
Sorry, I can't and won't support Manjaro.

**Comment by fushinari** [comment]
As for exactly why the issue itself is happening, the `libhandy` package in the Manjaro repos is outdated.

**Comment by fushinari** [comment]
I suggest Manjaro users to use the flatpak.

**Comment by aaronrancsik** [comment]
Thank you for the response. I got it.

**Comment by fushinari** [comment]
Really glad to see you took this well. I've had a Manjaro user swear at me via e-mail because an AUR package of mine was "not working on Manjaro" before. Thanks for being understanding, it's a surprisingly rare trait in Linux users for some reason.

**Comment by aaronrancsik** [comment]
> Really glad to see you took this well. I've had a Manjaro user swear at me via e-mail because an AUR package of mine was "not working on Manjaro" before. Thanks for being understanding, it's a surprisingly rare trait in Linux users for some reason.

It's time to change my distro... _(right now unfortunately I have no time for that (school and stuff))_

Joke aside.
I'ts my pleasure to use your and others free software. 
So thank you for the effort in free software. :) keep it up!

_By the way my problem solved by install 'Handy' from AUR
I use flatpak only if really no other option :D_

**Comment by fushinari** [comment]
Flatpak is amazing. OSTree and the permissions system especially. But I will admit that I too have had lots of issues with it, which is why I made the AUR package, so as to give some users at least one other choice.

I personally also have issues with how info about each flatpak is presented in GNOME Software. GNOME Builder for example is said to be "sandboxed" but it has permissions like Filesystem access, d-bus access and "sandbox escape". It should be made more clear when an application is only partially sandboxed.

But well... it's still amazing and I like how it works when it does work fine. So I try to use it where and where I can.

**Comment by apandada1** [comment]
`libhandy` version 1 is now on Manjaro repo, at least since beginning of January 2021.

**Comment by fushinari** [comment]
Yes, it should work on Manjaro just fine now. I will not officially support it though.

It's really nothing to be worried about, because if the Manjaro repo packages remain at least somewhat in sync with the official Arch repositories, most issues should be possible to reproduce on both.

You can report any issues you face on Manjaro with the AUR package too, but if it is Manjaro-specific and not applicable to Arch, I won't try to fix it because it will probably get fixed when they upgrade their packages anyway.

Sorry, but you should realize the implications of using the **Arch** User Repository from Manjaro. It's not anyone's fault, it's just how it is. :(
