### ISSUE TITLE
Move to Codeberg or GNOME GitLab

### ISSUE THREAD

**Issue by musicsd** [gi-lom/dialect#86]
GNOME GitLab and Codeberg are good places, because they are free and better; Why not move there?

**Comment by fushinari** [comment]
What are the advantages? I mean, other than that they're free? (Btw, isn't GitHub also technically free even if not free as in FOSS?)

**Comment by musicsd** [comment]
Do you really still think GitHub is a good place? With these recent catastrophes from GitHub, I can not trust it at all! GitHub boycotts Iranian users, mocks RTL, removes apps, is not open source, and more ...
I hate GitHub!

**Comment by fushinari** [comment]
The removal of apps and the block in Iran are not really GitHub's fault. Just the result of being based in USA and having to follow their law. I'd like to know more about the "mocks RTL" comment though, I've never heard of that. Sure, GitHub isn't the same place it was a few years ago and especially since becoming a wholly owned subsidiary of Microsoft, they've had to cave into political pressure a lot. But that's not to be confused with them turning evil or anything of the sort.

Still, I think moving to GNOME's Gitlab instance is reasonable. @rafaelmardojai what's your opinion?

**Comment by rafaelmardojai** [comment]
Personally I dislike Gitlab's UI and notification system. But if you're fine about moving to GNOME's Gitlab I'm fine too.

Pd. Codeberg also looks cools, the fact of being hosted in the EU give it some points. I will give it a try soon.

**Comment by fushinari** [comment]
Yeah, I like Codeberg, but we'd also miss features like the CI.

**Comment by fushinari** [comment]
Also, yes, I hate Gitlab's notification system too. (How is it even a notification system if it mails me everything and still doesn't show up in the to-do list?) I got used to the UI otherwise though (while I was slightly more actively contributing to Komikku). As for hosting, GNOME is also hosted in the US afaik, so there isn't much to gain from that either.

I don't think there's anything to gain by switching right now. Let's reconsider this if and when a need arises in the future. At least one of us will definitely have the source code, so no worries of suddenly disappearing like with some other repos. We'll just switch to another service if the time comes or something else changes.
