### ISSUE TITLE
Preferences menu screen not optimized for small screens

### ISSUE THREAD

**Issue by baarkerlounger** [gi-lom/dialect#90]
The Preferences menu dialog screen isn't currently adaptive enough for small, particularly portrait screens like on a PinePhone, making it difficult to use.

![dialect](https://user-images.githubusercontent.com/5101747/97806279-cef52380-1c52-11eb-9d9c-b901f5d65e1d.png)

**Comment by fushinari** [comment]
The Preferences window itself is still perfectly adaptive. Something else is going wrong. An initial guess is that Dialect is trying to open the Preferences window with its 'default_width' and 'default_height' instead of the device height and width. (Honestly that shouldn't be happening, so it's purely a guess.) I have no idea how to fix it either way lol.

Btw, are you sure this is a Dialect-specific issue? Have you tried opening the settings of any other adaptive application, like Lollypop or Komikku or anything else?

**Comment by baarkerlounger** [comment]
I've tried the preferences menu on Lollypop. It's not 100% perfect either (the very far right of the screen is slightly cut off) but it's close to fitting right and is useable.

**Comment by rafaelmardojai** [comment]
I thought Phosh compositor fitted every window in the screen.

The only difference we have with Lollypop is that we haven't set the window as modal.

**Comment by fushinari** [comment]
More info about your setup might help. Also, can someone else confirm the same bug? I feel like this isn't our bug but I want to solve it or at least work around it for now.

**Comment by rafaelmardojai** [comment]
This is and upstream (GTK3/libhandy) bug. 

See: https://twitter.com/KekunPlazas/status/1323007146578071552.

> That's a problem with GTK, on the Librem 5 we have downstream patches to fix that and some other issues, but the GTK version from the GNOME runtime doesn't have them, this affects all flatpaked apps.
>
> GTK 3 was declared frozen by its devs so we didn't submit any patch, hopefully they will accept changes for GTK 4.

Nothing we can do here.
