### ISSUE TITLE
Certain terms will fail to translate

### ISSUE THREAD

**Issue by fushinari** [gi-lom/dialect#95]
The only example of such a term that I've noticed so far is "exye". Typing that will give you "_error_".

In addition, it seems to set the src language to "hten". Thankfully, Dialect seems to handle it pretty gracefully on launch.

I haven't looked into how or why this is happening due to lack of time, but I'll look into it later.

**Comment by rafaelmardojai** [comment]
Translating `exye` from Auto in Dialect also fails.

**Comment by rafaelmardojai** [comment]
It fails with this error:
```
File "/app/share/dialect/dialect/window.py", line 363, in on_src_lang_changed
    name = LANGUAGES[code].capitalize()
KeyError: 'hten'
```

"exye" seems to be detected as both Haitian Creole and English, for some reason **py-googletrans** instead of returning a list, it returns both lang codes in a string.

It seems to be fixed upstream with this PR https://github.com/ssut/py-googletrans/pull/207. But the PR is from 29 Jul and[ last **py-googletrans** release](https://pypi.org/project/googletrans/#files) was in  Jun 14.

**Comment by fushinari** [comment]
I see... So an upstream bug that has already been fixed in master but not in a release yet. For the flatpak, we could patch it, right?

**Comment by rafaelmardojai** [comment]
> I see... So an upstream bug that has already been fixed in master but not in a release yet. For the flatpak, we could patch it, right?

Yes, or build py-googletrans for Flatpak from a more recent commit using github instead of pypi.

**Comment by fushinari** [comment]
I wanted to fix this for real but git version of py-googletrans is broken for me. Could you confirm, @rafaelmardojai ?

**Comment by rafaelmardojai** [comment]
The same change from [ff515051bd4760bc8d383d284c28d845f3b02b48] needs to be done in the search provider.
